name: CI-full-check

on:
  pull_request:
    types:
      - assigned
      - review_requested
  push:
    branches: 
      - main

jobs:
  action-inputs:
    uses: ./.github/workflows/integ-test-action-inputs.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  caching-config:
    uses: ./.github/workflows/integ-test-action-inputs-caching.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  execution-with-caching:
    uses: ./.github/workflows/integ-test-execution-with-caching.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  execution:
    uses: ./.github/workflows/integ-test-execution.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  gradle-versions:
    uses: ./.github/workflows/integ-test-gradle-versions.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-configuration-cache:
    uses: ./.github/workflows/integ-test-restore-configuration-cache.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-custom-gradle-home:
    uses: ./.github/workflows/integ-test-restore-custom-gradle-home.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-gradle-home:
    uses: ./.github/workflows/integ-test-restore-gradle-home.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-java-toolchain:
    uses: ./.github/workflows/integ-test-restore-java-toolchain.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  sample-kotlin-dsl:
    uses: ./.github/workflows/integ-test-sample-kotlin-dsl.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  sample-gradle-plugin:
    uses: ./.github/workflows/integ-test-sample-gradle-plugin.yml
    with:
      cache-key-prefix: ${{github.run_number}}-
