name: Test different action inputs

on:
  pull_request:
    types: [assigned, review_requested]
  push:
  workflow_dispatch:

env:
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: ${{github.workflow}}#${{github.run_number}}:${{github.run_attempt}}-

jobs:
  action-inputs:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Invoke with multi-line arguments
      uses: ./
      with:
        build-root-directory: __tests__/samples/groovy-dsl
        arguments: |
            --configuration-cache
            --build-cache
            -DsystemProperty=FOO
            -PgradleProperty=BAR
            test
            jar