 # make sure the action works on a clean machine without building
name: prod

on:
  pull_request:
  push:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Test use Gradle wrapper
      uses: ./
      with:
        build-root-directory: __tests__/samples/basic
        arguments: test
    - name: Test use defined Gradle version
      uses: ./
      with:
        gradle-version: rc
        build-root-directory: __tests__/samples/basic
        arguments: test
